"""Convert the supplied three-part MIDI's first eight bars to Dart constants.

Uses only the Python standard library. Run from the repository root. The score
keeps MIDI ticks so the app's fixed 128 BPM clock can map 32 beats to 15 seconds.
"""

from collections import defaultdict
from pathlib import Path
import hashlib
import struct

SOURCE = Path("assets/music/score_image_3part_transcription.mid")
OUTPUT = Path("lib/domain/midi_score_data.dart")
EXPECTED_SHA256 = "f1f87a116e70d1a00296f56deeab78d8066fd0df76a2318425e44b5766ef88ed"
BAR_END = 8 * 4 * 480


def variable(data, offset):
    value = 0
    while True:
        byte = data[offset]
        offset += 1
        value = (value << 7) | (byte & 0x7f)
        if byte < 128:
            return value, offset


def tracks(data):
    if data[:4] != b"MThd":
        raise ValueError("Not a MIDI file")
    header_size = struct.unpack_from(">I", data, 4)[0]
    format_, count, division = struct.unpack_from(">HHH", data, 8)
    if (format_, division) != (1, 480):
        raise ValueError("Expected format 1 at 480 ticks per beat")
    offset = 8 + header_size
    for _ in range(count):
        if data[offset:offset + 4] != b"MTrk":
            raise ValueError("Missing track")
        size = struct.unpack_from(">I", data, offset + 4)[0]
        track = data[offset + 8:offset + 8 + size]
        offset += 8 + size
        yield track


def notes(track):
    pos = tick = running = 0
    name = None
    active = defaultdict(list)
    result = []
    while pos < len(track):
        delta, pos = variable(track, pos)
        tick += delta
        status = track[pos]
        if status >= 0x80:
            pos += 1
            if status < 0xf0:
                running = status
        else:
            status = running
        if status == 0xff:
            kind = track[pos]
            size, pos = variable(track, pos + 1)
            payload = track[pos:pos + size]
            pos += size
            if kind == 3:
                name = payload.decode("utf-8")
        elif status in (0xf0, 0xf7):
            size, pos = variable(track, pos)
            pos += size
        else:
            kind = status & 0xf0
            width = 1 if kind in (0xc0, 0xd0) else 2
            first = track[pos]
            second = track[pos + 1] if width == 2 else 0
            pos += width
            key = (status & 0x0f, first)
            if kind == 0x90 and second:
                active[key].append(tick)
            elif kind == 0x80 or (kind == 0x90 and not second):
                if not active[key]:
                    raise ValueError(f"Unpaired note off: {key}")
                start = active[key].pop(0)
                if start < BAR_END:
                    result.append((start, min(tick, BAR_END) - start, first))
    if any(active.values()):
        raise ValueError("Unpaired note on")
    return name, sorted(result)


def main():
    raw = SOURCE.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_SHA256:
        raise ValueError(f"Unexpected MIDI SHA-256: {digest}")
    parts = {name: values for name, values in map(notes, tracks(raw)) if name in ("Melody", "Bass", "Piano")}
    if {name: len(values) for name, values in parts.items()} != {"Melody": 76, "Bass": 32, "Piano": 40}:
        raise ValueError("Unexpected first-eight-bar note counts")
    lines = [
        "// Generated by scripts/convert_midi_score.py from the bundled MIDI.",
        f"// SHA-256: {digest}",
        "// Each note stores [start tick, duration tick, MIDI pitch]. 480 ticks/beat.",
        "const midiScoreNotes = <List<List<int>>>[",
    ]
    for name in ("Melody", "Bass", "Piano"):
        lines.append(f"  // {name}: {len(parts[name])} notes")
        lines.append("  <List<int>>[")
        for start, duration, pitch in parts[name]:
            lines.append(f"    <int>[{start}, {duration}, {pitch}],")
        lines.append("  ],")
    lines.append("];")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print({name: len(values) for name, values in parts.items()})


if __name__ == "__main__":
    main()
