"""Convert the bundled public-domain MIDI templates to Dart constants.

Uses only the Python standard library. Run from the repository root:

    python scripts/convert_public_domain_scores.py

Each file in assets/music/public_domain is checked against manifest.json,
then its Melody, Bass and Chords tracks are written in the same
[start tick, duration tick, MIDI pitch] form as midi_score_data.dart, so the
arrangers can play them exactly like the original three-part score. The
Rhythm track is left out: the arrangers build the beat from the recordings.
"""

from pathlib import Path
import hashlib
import json

from convert_midi_score import notes, tracks

FOLDER = Path("assets/music/public_domain")
OUTPUT = Path("lib/domain/public_domain_scores.dart")
PARTS = ("Melody", "Bass", "Chords")
BAR_END = 8 * 4 * 480


def main():
    manifest = json.loads((FOLDER / "manifest.json").read_text(encoding="utf-8"))
    lines = [
        "// Generated by scripts/convert_public_domain_scores.py from",
        "// assets/music/public_domain. Each song keeps [Melody, Bass, Chords];",
        "// every note is [start tick, duration tick, MIDI pitch], 480 ticks/beat.",
        "const publicDomainScores = <String, List<List<List<int>>>>{",
    ]
    for template in manifest["templates"]:
        raw = (FOLDER / template["file"]).read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        if digest != template["sha256"]:
            raise ValueError(f"{template['file']}: unexpected SHA-256 {digest}")
        parts = {name: values for name, values in map(notes, tracks(raw)) if name in PARTS}
        if set(parts) != set(PARTS) or not all(parts.values()):
            raise ValueError(f"{template['file']}: missing one of {PARTS}")
        for values in parts.values():
            if any(start + length > BAR_END for start, length, _ in values):
                raise ValueError(f"{template['file']}: notes past 32 beats")
        lines.append(f"  // {template['title']} — {template['composer']}")
        lines.append(f"  '{template['id']}': <List<List<int>>>[")
        for name in PARTS:
            lines.append(f"    // {name}: {len(parts[name])} notes")
            lines.append("    <List<int>>[")
            for start, duration, pitch in parts[name]:
                lines.append(f"      <int>[{start}, {duration}, {pitch}],")
            lines.append("    ],")
        lines.append("  ],")
        print(template["id"], {name: len(parts[name]) for name in PARTS})
    lines.append("};")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
